import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Hello Next Js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold ">Hello world!</h1>
      <p className={styles.primaryColor}>Hello world! SCSS</p>
    </div>
  );
}
