import Head from "next/head";
import styles from "../styles/Home.module.scss";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Beautiv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className="hidden md:block">
          Home Page
        </div>
      <footer>
        
      </footer>
    </div>
  );
}
